spring:
  datasource:
    url: jdbc:mysql://localhost:3306/remember?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
    data:
      web:
        pageable:
          default-page-size: 10

jwt:
  secret-key: chanseokchanseokchanseokchanseokchanseok
  expiration-time: 86400000